default: &default
  adapter: postgresql # o mysql2 si est√°s usando MySQL
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: riwi_coffee_development

test:
  <<: *default
  database: riwi_coffee_test

production:
  <<: *default
  database: riwicofffee # Cambia esto al nombre de tu base de datos en Render
  url: <%= ENV['DATABASE_URL'] %> # O simplemente coloca la URL directamente
